def horoscope():
	M=input("enter the month and date :\n")
	S=M.split()
	month=S[0]
	day=int(S[1])
	print("YOUR ZODIAC SIGN IS:")
	if(month=="december"):
		if(day>21):
			print("Capricorn")
		else:
			print("sagittarius")
	elif(month=="january"):
		if(day>19):
			print("aquarius")
		else:
			print("capricorn")
	elif(month=="february"):
		if(day>19):
			print("Pisces")
		else:
			print("aquarius")
	elif(month=="march"):
		if(day>20):
			print("Aries")
		else:
			print("Pisces")
	elif(month=="april"):
		if(day>19):
			print("Taurus")
		else:
			print("Aries")
	elif(month=="may"):
		if(day>20):
			print("Gemini")
		else:
			print("Taurus")
	elif(month=="june"):
		if(day>20):
			print("cancer")
		else:
			print("Gemini")
	elif(month=="july"):
		if(day>22):
			print("Leo")
		else:
			print("cancer")
	elif(month=="august"):
		if(day>22):
			print("Virgo")
		else:
			print("Leo")
	elif(month=="september"):
		if(day>22):	
			print("Libra")
		else:
			print("Virgo")
	elif(month=="october"):
		if(day>22):
			print("Scorpio")
		else:
			print("Lobra")
	elif(month=="november"):
		if(day>21):
			print("Sagittarius")
		else:
			print("Scorpio")
	else:
		print("please enter a valid month and date")	
horoscope()